In [1]:
import pandas as pd
print(pd)

<module 'pandas' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [8]:
df= pd.read_csv('netflix.csv')
df.head()

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies

In [10]:
#Select TV Show released in year 2019
df[(df.release_year == 2019) & (df.type == 'TV Show')]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
34,80221550,TV Show,Archibald's Next Big Thing,NaN,"Tony Hale, Rosamund Pike, Jordan Fisher, Chels...",NaN,2019,TV-Y7,1 Season,"Kids' TV, TV Comedies"
39,80178151,TV Show,The Spy,NaN,"Sacha Baron Cohen, Noah Emmerich, Hadar Ratzon...",France,2019,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers"
99,80225885,TV Show,Bard of Blood,NaN,"Emraan Hashmi, Viineet Kumar, Sobhita Dhulipal...",India,2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,..."
101,80218107,TV Show,Dragons: Rescue Riders,NaN,"Nicolas Cantu, Brennley Brown, Zach Callison, ...",NaN,2019,TV-Y,1 Season,"Kids' TV, TV Comedies"
103,80220715,TV Show,Skylines,NaN,"Edin Hasanovic, Peri Baumeister, Murathan Musl...",NaN,2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas"
...,...,...,...,...,...,...,...,...,...,...
6198,80189829,TV Show,The Protector,NaN,"Çağatay Ulusoy, Ayça Ayşin Turan, Hazar Ergüçl...",Turkey,2019,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
6204,80091341,TV Show,Cuckoo,NaN,"Andy Samberg, Taylor Lautner, Greg Davies, Hel...",United Kingdom,2019,TV-14,5 Seasons,"British TV Shows, International TV Shows, TV C..."
6206,80173174,TV Show,Samantha!,NaN,"Emmanuelle Araújo, Douglas Silva, Sabrina Nona...",Brazil,2019,TV-MA,2 Seasons,"International TV Shows, TV Comedies"
6215,80066227,TV Show,Crazy Ex-Girlfriend,NaN,"Rachel Bloom, Vincent Rodriguez III, Santino F...",United States,2019,TV-14,4 Seasons,"Romantic TV Shows, TV Comedies"
6219,80186475,TV Show,Pokémon the Series,NaN,"Sarah Natochenny, Laurie Hymes, Jessica Paquet...",Japan,2019,TV-Y7-FV,2 Seasons,"Anime Series, Kids' TV"

In [13]:
#Select Movies between year 2018 to 2020
df[(df.release_year>2017) & (df.release_year<2021) & (df.type == 'Movie')]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
27,80203094,Movie,City of Joy,Madeleine Gavin,NaN,"United States,",2018,TV-MA,77 min,Documentaries
30,80988892,Movie,Next Gen,"Kevin R. Adams, Joe Ksander","John Krasinski, Charlyne Yi, Jason Sudeikis, M...","China, Canada, United States",2018,TV-PG,106 min,"Children & Family Movies, Comedies, Sci-Fi & F..."
31,80239639,Movie,Sierra Burgess Is A Loser,Ian Samuels,"Shannon Purser, Kristine Froseth, RJ Cyler, No...",United States,2018,PG-13,106 min,"Comedies, Romantic Movies"
32,80159586,Movie,The Most Assassinated Woman in the World,Franck Ribière,"Anna Mouglalis, Niels Schneider, André Wilms, ...","Belgium, United Kingdom, United States",2018,TV-MA,102 min,"Dramas, International Movies, Thrillers"
...,...,...,...,...,...,...,...,...,...,...
5476,80210602,Movie,I Am Maris,Laura VanZee Taylor,Maris Degener,United States,2018,TV-14,54 min,Documentaries
5477,81088283,Movie,Jesus: Countdown to Calvary,Gerry Hoban,Hugh Bonneville,"Ireland, United States, France",2018,TV-14,53 min,"Documentaries, Faith & Spirituality"
5485,81052280,Movie,Pinky Memsaab,Shazia Ali Khan,"Hajira Yamin, Kiran Malik, Adnan Jaffar, Sunny...","Pakistan, United Arab Emirates",2018,TV-14,124 min,"Dramas, Independent Movies, International Movies"
5497,81088284,Movie,The World's Most Wanted Animal,Victoria Bromley,Maria Diekmann,United Kingdom,2018,TV-PG,53 min,Documentaries
5520,80244992,Movie,Ethirmarai,NaN,"Ramanathan, Rakesh",India,2018,TV-14,91 min,"International Movies, Music & Musicals, Thrillers"

In [16]:
#Select shows aired only in United states
df[df.country.str.contains('United States') == True]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers"
...,...,...,...,...,...,...,...,...,...,...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies"
6226,70243132,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh..."
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies"

In [27]:
#Select cast of the TV shows  telecasted in year 2019 and had rating R
df[(df.release_year == 2019) & (df.type == 'TV Show') & (df.rating == 'R')].cast

Series([], Name: cast, dtype: object)

In [30]:
df.drop(['show_id'],axis=1)

,type,title,director,cast,country,release_year,rating,duration,listed_in
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies
...,...,...,...,...,...,...,...,...,...
6229,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies
6231,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies
6232,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas"
6233,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies"

In [35]:
#Add column duration_min such that it’s type is numeric [use column duration]
df['duration_min'] = df.duration.apply(lambda x: x.split()[0])
df

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,duration_min
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies",90
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy,94
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV,1
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV,1
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies,99
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...",13
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies,4
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies,60
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas",2
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",10